[package]
name = "consensus-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
n42-tx-types.workspace = true
n42-clique-utils.workspace = true
n42-engine-primitives.workspace = true
merkle_db_rs.workspace=true
pubsub-mem.workspace=true
n42-primitives.workspace = true
n42-clique.workspace = true
# reth
#reth-beacon-consensus.workspace = true
reth-storage-errors.workspace = true
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-engine-primitives.workspace = true
reth-engine-tree.workspace = true
reth-evm.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-ethereum-primitives.workspace = true
reth-payload-builder.workspace = true
reth-payload-primitives.workspace = true
reth-payload-validator.workspace = true
reth-provider.workspace = true
reth-prune.workspace = true
reth-rpc-types-compat.workspace = true
reth-rpc.workspace = true
reth-transaction-pool.workspace = true
reth-stages-api.workspace = true
reth-network.workspace = true
reth-eth-wire-types.workspace = true
reth-network-api.workspace = true
reth-tokio-util.workspace = true
reth-node-types.workspace = true
reth-node-api.workspace = true
reth-network-p2p.workspace = true
reth-primitives-traits.workspace = true

# alloy
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-serde.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-eips.workspace = true
alloy-consensus.workspace = true

# async
tokio.workspace = true
tokio-stream.workspace = true
futures-util.workspace = true

# metrics
reth-metrics = { workspace = true }
metrics = { workspace = true }

# http
reqwest.workspace = true

# misc
hex.workspace = true
sled.workspace = true
serde_json.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
arbitrary.workspace = true
integer-sqrt.workspace = true
thiserror.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types-beacon.workspace = true
serde.workspace = true
nix.workspace = true
eyre.workspace = true
tracing.workspace = true
schnellru.workspace = true
itertools.workspace = true
alloy-sol-types.workspace = true
blst.workspace = true

op-alloy-rpc-types-engine = { workspace = true, optional = true }

[lints]
workspace = true
